# Workflow to be executed on a PR rasie to main, code needs to be build, scanned before merging and deployed to DEV for testing
name: BuildAspDotNetCore

on:
# We also want to be able to run this manually from Github
  workflow_call:
    inputs:
      dotnetverion:
        required: true
        type: string
  
#env:
  #CONFIGURATION: release
  #CONFIGURATION: feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ inputs.dotnetverion }}'  
        #dotnet-version: '6.0.x'  ${{ inputs.dotnetverion }}
    
    - name: Restore
      run: dotnet restore src/ContosoUniversity.sln
    
    - name: Build
      #run: dotnet build src/ContosoUniversity.sln --configuration ${{ env.CONFIGURATION }} --no-restore
      run: dotnet build src/ContosoUniversity.sln  --no-restore
    
    - name: Test
      run: dotnet test src/ContosoUniversity.Test/ContosoUniversity.Test.csproj --verbosity normal --logger trx --results-directory TestResults
      
    - name: Publish APP
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApp src/ContosoUniversity.WebApplication/ContosoUniversity.WebApplication.csproj

    - name: Publish API
      run: dotnet publish --configuration ${{ env.CONFIGURATION }} --output PublishApi src/ContosoUniversity.API/ContosoUniversity.API.csproj
    
