name: Build JAR app

on:
  workflow_call:
    inputs:
      packagepath: 
        required: true
        type: string
      javaversion:
        required: true
        type: string
      mavenpath:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'

#cd ./hibernate-orm-panache-quickstart
      - name: Build with Maven
        run: |
             cd ./{{ inputs.mavenpath}}
             mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ inputs.packagepath }}/*.jar' 
          #path: '${{ github.workspace }}/hibernate-orm-panache-quickstart/target/*.jar'
          
