name: Deploy JAR app

on:
  workflow_call:
    inputs:
      packagename: 
        required: true
        type: string
      appname: 
        required: true
        type: string
      slotname:
        required: true
        type: string
      
        
    secrets:
      AZURE_CREDENTIALS:
        required: true    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ inputs.packagename }} 
          #name: java-app
          

      - name: Azure Login
        uses: Azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: set appsettings
        run: az webapp config appsettings set -g "akkitestRG1" -n "akkipayaljavy" --settings 'DBHOST=akkiquarkuspostgres' 'DBNAME=fruits' 'DBUSER=demoadmin' 'DBPASS=88e3-1cf40c6144fd' 'PORT=8080' 'WEBSITES_PORT=8080' 
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.appname }}
          slot-name: ${{ inputs.slotname }}
          package: '${{ github.workspace }}/*.jar'
          #app-name: 'akkipayaljavy' appname
          #slot-name: 'Production'  slotname
          
      
