name: Zaporxy_DAST

on:
  workflow_call:
    inputs:
      URL:
        required: true
        type: string
      
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the website using ZAP 
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: '${{ inputs.URL }}'
